<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Authors>Riccardo Sadocchi</Authors>
		<Description>Progetto di esempio legato al libro Basi di programmazione a oggetti</Description>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="DTO\" />
		<Folder Include="wwwroot\favicon\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NLog.Extensions.Logging" Version="6.1.1" />
		<PackageReference Include="NLog.Schema" Version="6.1.0" />
		<PackageReference Include="NLog.Web.AspNetCore" Version="6.1.1" />
	</ItemGroup>
</Project>
